# Gradle
# specific path build
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - kotlinlibs/common/*
      - kotlinlibs/frontend-angular/*
      - framework/*
      - build.gradle
      - gradle.properties
      - settings.gradle
      - gradle/*

pool:
  name: 'Default'

steps:
  - template: ../../cicd-templates/configure-local-jdk.yml
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'kotlinlibs:frontend-angular:release'