package com.cramsan.ps2link.network.models.content.character

data class Day(
    var d01: String? = null,
    var d02: String? = null,
    var d03: String? = null,
    var d04: String? = null,
    var d05: String? = null,
    var d06: String? = null,
    var d07: String? = null,
    var d08: String? = null,
    var d09: String? = null,
    var d10: String? = null,
    var d12: String? = null,
    var d13: String? = null,
    var d14: String? = null,
    var d15: String? = null,
    var d16: String? = null,
    var d17: String? = null,
    var d18: String? = null,
    var d19: String? = null,
    var d20: String? = null,
    var d21: String? = null,
    var d22: String? = null,
    var d23: String? = null,
    var d24: String? = null,
    var d25: String? = null,
    var d26: String? = null,
    var d27: String? = null,
    var d28: String? = null,
    var d29: String? = null,
    var d30: String? = null,
    var d31: String? = null,
)
