package com.cramsan.ps2link.network.models.content.character

import kotlinx.serialization.Serializable

@Serializable
data class Day(
    var d01: String? = null,
    val d02: String? = null,
    val d03: String? = null,
    val d04: String? = null,
    val d05: String? = null,
    val d06: String? = null,
    val d07: String? = null,
    val d08: String? = null,
    val d09: String? = null,
    val d10: String? = null,
    val d12: String? = null,
    val d13: String? = null,
    val d14: String? = null,
    val d15: String? = null,
    val d16: String? = null,
    val d17: String? = null,
    val d18: String? = null,
    val d19: String? = null,
    val d20: String? = null,
    val d21: String? = null,
    val d22: String? = null,
    val d23: String? = null,
    val d24: String? = null,
    val d25: String? = null,
    val d26: String? = null,
    val d27: String? = null,
    val d28: String? = null,
    val d29: String? = null,
    val d30: String? = null,
    val d31: String? = null,
) {
    companion object {
        fun newInstance() = Day(
            d01 = null,
            d02 = null,
            d03 = null,
            d04 = null,
            d05 = null,
            d06 = null,
            d07 = null,
            d08 = null,
            d09 = null,
            d10 = null,
            d12 = null,
            d13 = null,
            d14 = null,
            d15 = null,
            d16 = null,
            d17 = null,
            d18 = null,
            d19 = null,
            d20 = null,
            d21 = null,
            d22 = null,
            d23 = null,
            d24 = null,
            d25 = null,
            d26 = null,
            d27 = null,
            d28 = null,
            d29 = null,
            d30 = null,
            d31 = null,
        )
    }
}
