# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# specific path build
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - auraxiscontrolcenter/*
    - framework/*
    - build.gradle
    - gradle.properties
    - settings.gradle
    - gradle/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: android-manifest-version@1
  inputs:
    sourcePath: '$(system.defaultworkingdirectory)/auraxiscontrolcenter/src/main/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    versionCodeOffset: '38'
    versionName: 
    printFile: true
    
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'auraxiscontrolcenter:release '

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/auraxiscontrolcenter-release-unsigned.apk'
    apksign: true
    zipalign: false
    apksignerKeystoreFile: $(KeyStoreFile)
    apksignerKeystorePassword: $(KeyStorePassword)
    apksignerKeystoreAlias: $(KeyStoreAlias)
    apksignerKeyPassword: $(KeyPassword)

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/auraxiscontrolcenter-stage-unsigned.apk'
    apksign: true
    zipalign: false
    apksignerKeystoreFile: $(StageKeyStoreFile)
    apksignerKeystorePassword: $(StageKeyStorePassword)
    apksignerKeystoreAlias: $(StageKeyStoreAlias)
    apksignerKeyPassword: $(StageKeyPassword)

- task: CopyFiles@2
  inputs:
    sourceFolder: $(system.defaultworkingdirectory)/auraxiscontrolcenter/build/outputs/apk/
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'App Center'
    appSlug: 'cramsan/AuraxisControlCenter'
    appFile: 'auraxiscontrolcenter/build/outputs/apk/stage/auraxiscontrolcenter-stage-unsigned.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'Release Notes: TBD'
    destinationType: 'groups'
    distributionGroupId: '368466ff-a4a5-49e3-9f13-7ed11ac71160, 00000000-0000-0000-0000-000000000000'
