# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# specific path build
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - petproject/*
    - framework/*
    - build.gradle
    - gradle.properties
    - settings.gradle
    - gradle/*

pool:
  vmImage: 'macOS-latest'

steps:

- task: android-manifest-version@1
  inputs:
    sourcePath: '$(system.defaultworkingdirectory)/petproject/app/src/main/AndroidManifest.xml'
    versionCodeOption: 'buildid'
    versionCode: '$(Build.BuildId)'
    versionCodeOffset: '10'
    versionName: 
    printFile: true

- task: Gradle@2
  inputs:
    options: '-PpetProjectAppCenterId=$(ps2linkAppCenterId) -PcommitId=$(build.sourceVersion)'
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'petproject:app:release'

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/app-prod-release-unsigned.apk'
    apksign: true
    zipalign: false
    apksignerKeystoreFile: $(KeyStoreFile)
    apksignerKeystorePassword: $(KeyStorePassword)
    apksignerKeystoreAlias: $(KeyStoreAlias)
    apksignerKeyPassword: $(KeyPassword)

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/app-preprod-release-unsigned.apk'
    apksign: true
    zipalign: false
    apksignerKeystoreFile: $(StageKeyStoreFile)
    apksignerKeystorePassword: $(StageKeyStorePassword)
    apksignerKeystoreAlias: $(StageKeyStoreAlias)
    apksignerKeyPassword: $(StageKeyPassword)

- task: CopyFiles@2
  inputs:
    sourceFolder: $(system.defaultworkingdirectory)/petproject/app/build/outputs/apk/
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'App Center'
    appSlug: 'cramsan/Pet-Project-1'
    appFile: 'petproject/app/build/outputs/apk/prod/release/app-prod-release-unsigned.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'Release Notes: TBD'
    destinationType: 'groups'
    distributionGroupId: '00000000-0000-0000-0000-000000000000'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'App Center'
    appSlug: 'cramsan/PetProject-PreProd'
    appFile: 'petproject/app/build/outputs/apk/preprod/release/app-preprod-release-unsigned.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: '$(build.sourceVersionMessage)'
    destinationType: 'groups'
    distributionGroupId: '00000000-0000-0000-0000-000000000000'
